# Generated by Django 2.0 on 2020-07-22 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_by', models.CharField(max_length=100)),
                ('opened_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_date', models.DateTimeField(null=True)),
                ('office_description', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('inprogress', 'Inprogress'), ('closed', 'Closed')], default='pending', max_length=10)),
                ('done_by', models.CharField(max_length=100)),
                ('closed_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('added_by', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.Type'),
        ),
    ]
